Repository RTX2080-UF/gatorshare-frontend, pull requests merged in 2022-02, with the labels that each got.

#24 Added code structure and main page skeleton
  src/App.css
  src/App.js
  src/components/Main.js
  src/components/NavBar.js
  src/components/README.md
  src/components/SideBar.js
  src/data/README.md
  src/index.css
  src/pages/README.md
  src/theme/README.md
  src/theme/colors.js
  src/utils/README.md
Labels: enhancement

#29 Added logos and favicons. Fixes #28
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  src/assets/logo_square_transparent.svg
  src/assets/logo_wide.svg
  src/logo.svg
Labels: enhancement, Sprint 1

#27 Added data flow. Fixes #26
  src/data/Api.js
  src/data/Data.js
  src/data/Demo.js
Labels: enhancement, Sprint 1

#30 Navbar changes. Fixes #22
  package-lock.json
  package.json
  src/components/LineSeparator.js
  src/components/NavBar.css
  src/components/NavBar.js
  src/images/pp.jfif
Labels: enhancement, Sprint 1

#31 Created the post component. Fixes #16
  src/App.css
  src/components/Post.js
  src/components/UserMini.js
  src/data/Demo.js
  src/index.css
  src/utils/Utils.js
Labels: enhancement, Sprint 1

#32 Added Home Page Component. Fixes #15
  src/App.css
  src/components/Main.js
  src/pages/Home.js
Labels: enhancement, Sprint 1

#33 Finishing the navbar. Replaced text with logo
  src/assets/pp.jfif
  src/components/NavBar.js
Labels: enhancement, Sprint 1

#35 Added posts to home page. Fix #19
  package-lock.json
  src/App.css
  src/assets/logo_wide.png
  src/assets/logo_wide.svg
  src/assets/pp.jfif
  src/components/Main.js
  src/components/NavBar.css
  src/components/NavBar.js
  src/components/UserMini.js
  src/components/UserNav.js
  src/data/Demo.js
  src/index.css
  src/pages/Home.js
  yarn.lock
Labels: enhancement, Sprint 1

#39 Create post modal has been created #34
  SPRINT1.md
  package-lock.json
  src/App.css
  src/components/CreatePostModal.js
  src/components/NavBar.css
  src/components/NavBar.js
Labels: enhancement, Sprint 1

#41 Added Post Details. Fixes #40
  package-lock.json
  package.json
  src/App.css
  src/components/Main.js
  src/components/NavBar.js
  src/components/Post/Post.js
  src/components/Post/PostDetails.js
  src/data/Demo.js
  src/index.css
  src/pages/Home.js
  yarn.lock
Labels: enhancement

#42 Added Sidebar menu. Fixes #38
  src/components/Main.js
  src/components/SideBar.js
  src/components/SideBar/SideBar.js
  src/components/SideBar/SideBarItem.js
  src/pages/Home.js
Labels: enhancement

#44 Created comments component and added to post
  src/components/Comment/Comment.js
  src/components/Post/Post.js
  src/components/Post/PostDetails.js
  src/data/Demo.js
Labels: enhancement

#46 Fixing the netlify routing issue #45
  public/_redirects
Labels: bug

#49 Added data call for create comment
  src/components/Post/PostDetails.js
  src/data/Demo.js
  src/utils/Utils.js
Labels: enhancement
