Repository RTX2080-UF/gatorshare-frontend, pull requests merged in 2022-03, with the labels that each got.

#54 Added boilerplate code for APIs
  src/data/Api.js
  src/data/Data.js
  src/data/Demo.js
  src/pages/Home.js
Labels: Sprint 2

#58 1 create login component 1
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/App_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/assets/loginimg.jpeg
  src/components/BGImage.js
  src/components/CreatePostModal.js
  src/components/Entry.js
  src/components/Login/Login.js
  src/components/Main.js
  src/components/NavBar.js
  yarn.lock
Labels: Sprint 2

#61 2 register user component 1
  cypress/integration/SignupTest.js
  src/components/Entry.js
  src/components/Signup/Signup.js
Labels: Sprint 2

#63 Onboarding Page
  src/App.css
  src/App.js
  src/components/Entry.js
  src/components/Onboarding/Category.js
  src/components/Onboarding/User.js
  src/data/Api.js
  src/data/Demo.js
  src/pages/Onboarding.js
Labels: enhancement

#62 1 create login component 1
  SPRINT2.md
  cypress/integration/LoginTests.js
  src/assets/loginimg.jpeg
  src/assets/loginimg.webp
  src/components/BGImage.js
Labels: Sprint 2

#65 Session Utils
  src/data/Api.js
  src/utils/SessionUtils.js
Labels: enhancement

#68 Fixed bad variable routing for Post api response
  src/assets/avatar_placeholder.png
  src/components/Entry.js
  src/components/Main.js
  src/components/Post/Post.js
  src/components/Post/PostDetails.js
  src/components/UserMini.js
  src/data/Api.js
  src/pages/Home.js
  src/utils/Utils.js
Labels: bug

#71 Updated Current User from DB and then referenced everywhere else from…
  src/components/Main.js
  src/components/NavBar.js
  src/data/Api.js
  src/utils/SessionUtils.js
Labels: enhancement

#72 67 loginrequest
  src/components/Login/Login.js
  src/data/Api.js
Labels: Sprint 2

#73 Added Jest
  .gitignore
  babel.config.js
  package-lock.json
  package.json
  sessionutils.test.js
  src/App.test.js
  src/setupTests.js
  src/utils/SessionUtils.js
  yarn.lock
Labels: enhancement

#74 cypress viewport width and height adjusted
  cypress.json
Labels: Sprint 2

#75 Jest minor changes
  src/components/NavBar.js
  src/pages/Home.js
  src/utils/SessionUtils.js
Labels: enhancement

#80 79 register service call
  cypress/integration/LoginTests.js
  cypress/integration/SignupTest.js
  src/components/Login/Login.js
  src/components/NavBar.js
  src/components/Signup/Signup.js
Labels: Sprint 3
