Repository RTX2080-UF/gatorshare-frontend, pull requests merged in 2022-04, with the labels that each got.

#85 Search screen
  src/App.css
  src/assets/search-splash.png
  src/components/Entry.js
  src/components/NavBar.js
  src/components/SideBar/SideBar.js
  src/components/modals/SearchFilter/SearchFilter.js
  src/pages/Search.js
Labels: enhancement

#86 Profile and settings UI
  cypress/integration/SettingsTest.js
  src/App.css
  src/components/Entry.js
  src/components/Login/ForgotPassword.js
  src/components/Login/Login.js
  src/components/Main.js
  src/components/NavBar.js
  src/components/Settings/Notifications.js
  src/components/Settings/Profile.js
  src/components/Settings/Security.js
  src/components/Settings/Settings.js
  src/components/Settings/SettingsPath.js
  src/components/Settings/SettingsSideBar.js
  src/components/Settings/SettingsSideBarItem.js
  src/pages/Home.js
Labels: Sprint 3

#88 Home Screen
  src/App.css
  src/components/Entry.js
  src/components/Main.js
  src/components/NavBar.js
  src/components/Post/Post.js
  src/components/Post/PostDetails.js
  src/components/Post/PostMini.js
  src/components/Settings/SettingsSideBarItem.js
  src/components/SideBar/SideBar.js
  src/data/Data.js
  src/data/Demo.js
  src/pages/Home.js
  src/pages/Posts.js
  src/utils/Utils.js
Labels: enhancement

#89 Sprint3 documentation
  README.md
  SPRINT3.md
  cypress/integration/SettingsTest.js
  src/assets/sprint3.gif
  src/components/NavBar.js
Labels: Sprint 3

#92 Sprint3
  SPRINT3.md
  src/assets/jest_sprint3.jpeg
Labels: Sprint 3

#95 signup service call integrated
  src/components/Login/Login.js
  src/components/Signup/Signup.js
  src/data/Api.js
  src/data/Data.js
Labels: Sprint 4

#98 Added Notifications
  src/App.css
  src/components/NavBar.js
  src/components/SideBar/SideBar.js
  src/components/modals/Notifications/Notifications.js
  src/data/Api.js
Labels: enhancement

#101 100 Comment
  src/App.css
  src/components/Comment/Comment.js
  src/components/Entry.js
  src/components/NavBar.js
  src/components/Post/Post.js
  src/components/Post/PostDetails.js
  src/components/UserMini.js
  src/components/UserNav.js
  src/components/modals/Notifications/Notifications.js
  src/data/Api.js
  src/pages/UserProfile.js
  src/utils/SessionUtils.js
Labels: enhancement

#105 Added Search APIs
  src/App.css
  src/data/Api.js
  src/pages/Search.js
Labels: enhancement

#106 Integration
  src/components/Comment/Comment.js
  src/components/CreatePostModal.js
  src/components/HandleQuery.js
  src/components/Login/ChangePassword.js
  src/components/Login/ForgotPassword.js
  src/components/Login/Login.js
  src/components/NavBar.js
  src/components/Onboarding/Category.js
  src/components/Post/Post.js
  src/components/Post/PostDetails.js
  src/components/Settings/Security.js
  src/components/Settings/SettingsSideBarItem.js
  src/components/Signup/Signup.js
  src/components/modals/Notifications/Notifications.js
  src/pages/Home.js
  src/pages/Posts.js
  yarn.lock
Labels: Sprint 4
